#include "search.h"

// Best move in the position
static int best_move;

// Half move (i.e. one move by black or white)
static int ply = 0;

// Attacker by row, Victim by column
// Generated by subtracting attacker from victim, adding queen value, then dividing by smallest number
static int mvv_lva_table[6][6] = {
//   P    N    B    R    Q    K
    {42,  47,  48,  54,  72, 438}, // P
    {37,  38,  39,  45,  63, 436}, // N
    {36,  37,  38,  44,  62, 435}, // B
    {32,  31,  32,  38,  56, 434}, // R
    {4,   13,  14,  20,  38, 436}, // Q
    {0,   1,   2,   8,   24, 400}  // K
};
//Table is used for mvv-lva move ordering



int quiescence(int alpha, int beta){
    // Evaluate position
    int evaluation = evaluate();
    
    // Beta cutoff
    if(evaluation >= beta){
        // Node fails high
        return beta;
    }

    // Better move
    if(evaluation > alpha){
        alpha = evaluation;
    }

    moves move_list;
    generate_moves(&move_list);
    prune_to_quiescence(&move_list);
    sort_moves(&move_list);
    for(int count = 0; count < move_list.count; count++){
        ply++;
        // If move is illegal take it back
        if(make_move(move_list.moves[count]) == 0){
            ply--;
            continue;
        }
        // Recursively call negamax with negative parameters
        int score = -quiescence(-beta, -alpha);

        take_back();
        ply--;
        
        // Beta cutoff
        if(score >= beta){
            // Node fails high
            return beta;
        }

        // Better move
        if(score > alpha){
            alpha = score;
        }
    }
    // Move fails low
    return alpha;
}

int negamax(int alpha, int beta, int depth){
    if(depth == 0){
        return quiescence(alpha, beta);
    }
    // Used for checkmate detection
    int in_check = is_square_attacked((side == white) ? get_ls1b_index(bitboards[K]) : get_ls1b_index(bitboards[k]), side ^ 1);

    int legal_moves = 0;
    int best_sofar = 0;
    int old_alpha = alpha;

    // Generate moves for move list
    moves move_list;
    generate_moves(&move_list);
    sort_moves(&move_list);
    for(int count = 0; count < move_list.count; count++){
        ply++;
        // If move is illegal take it back
        if(make_move(move_list.moves[count]) == 0){
            ply--;
            continue;
        }
        legal_moves++;
        // Recursively call negamax with negative parameters
        int score = -negamax(-beta, -alpha, depth-1);
        take_back();
        ply--;
        
        // Beta cutoff
        if(score >= beta){
            // Node fails high
            return beta;
        }

        // Better move
        if(score > alpha){
            alpha = score;
            // Move is a root
            if(ply == 0){
                best_sofar = move_list.moves[count];
            }
        }
    }
    // Detect checkmate
    if(legal_moves == 0){
        if(in_check){
            return -49000 + ply;
        }
        // Stalemate
        else{
            return 0;
        }
    }
    // If change in alpha then best_move changes
    if(old_alpha != alpha){
        best_move = best_sofar;
    }
    // Move fails low
    return alpha;
}


int get_move_score(int move) {
    if(!get_capture(move)){
        return 0;
    }

    int target = get_target(move);
    int attacker = get_piece(move);
    int victim = 0;

    // Find victim by finding intersection of square and piece
    for(int piece = P; piece <= k; piece++) {
        U64 bitboard = bitboards[piece];
        if(bitboard & (1ULL << target)) {
            victim = piece;
            break;
        }
    }
    // Simplify black into white for lookup
    attacker %= 6;
    victim %= 6;

    // Get mvv_lva lookup of attacker and victim
    return mvv_lva_table[attacker][victim];
}

int compare_moves(const void *a, const void *b) {
    const int *move_list_a = (const int *)a;
    const int *move_list_b = (const int *)b;

    int score_a = get_move_score(*move_list_a);
    int score_b = get_move_score(*move_list_b);

    return score_b - score_a;
}

void sort_moves(moves *move_list) {
    qsort(move_list->moves, move_list->count, sizeof(int), compare_moves);
}

// Find best move given a position
void search_position(int depth){
    ply = 0;
    best_move = 0;
    pos_num = 0;
    negamax(-50000, 50000, depth);
    printf("bestmove ");
    print_move(best_move);
    printf("\n");
}

